// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToDownloadList(arg1, arg2) {
  return window['go']['backend_golang']['App']['AddToDownloadList'](arg1, arg2);
}

export function CloseMidiPort() {
  return window['go']['backend_golang']['App']['CloseMidiPort']();
}

export function ContinueDownload(arg1) {
  return window['go']['backend_golang']['App']['ContinueDownload'](arg1);
}

export function ConvertData(arg1, arg2, arg3, arg4) {
  return window['go']['backend_golang']['App']['ConvertData'](arg1, arg2, arg3, arg4);
}

export function ConvertGGML(arg1, arg2, arg3, arg4) {
  return window['go']['backend_golang']['App']['ConvertGGML'](arg1, arg2, arg3, arg4);
}

export function ConvertModel(arg1, arg2, arg3, arg4) {
  return window['go']['backend_golang']['App']['ConvertModel'](arg1, arg2, arg3, arg4);
}

export function ConvertSafetensors(arg1, arg2) {
  return window['go']['backend_golang']['App']['ConvertSafetensors'](arg1, arg2);
}

export function ConvertSafetensorsWithPython(arg1, arg2, arg3) {
  return window['go']['backend_golang']['App']['ConvertSafetensorsWithPython'](arg1, arg2, arg3);
}

export function CopyFile(arg1, arg2) {
  return window['go']['backend_golang']['App']['CopyFile'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['backend_golang']['App']['DeleteFile'](arg1);
}

export function DepCheck(arg1) {
  return window['go']['backend_golang']['App']['DepCheck'](arg1);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['backend_golang']['App']['DownloadFile'](arg1, arg2);
}

export function FileExists(arg1) {
  return window['go']['backend_golang']['App']['FileExists'](arg1);
}

export function GetAbsPath(arg1) {
  return window['go']['backend_golang']['App']['GetAbsPath'](arg1);
}

export function GetPlatform() {
  return window['go']['backend_golang']['App']['GetPlatform']();
}

export function GetProxyPort() {
  return window['go']['backend_golang']['App']['GetProxyPort']();
}

export function GetPyError() {
  return window['go']['backend_golang']['App']['GetPyError']();
}

export function InstallPyDep(arg1, arg2) {
  return window['go']['backend_golang']['App']['InstallPyDep'](arg1, arg2);
}

export function IsPortAvailable(arg1) {
  return window['go']['backend_golang']['App']['IsPortAvailable'](arg1);
}

export function ListDirFiles(arg1) {
  return window['go']['backend_golang']['App']['ListDirFiles'](arg1);
}

export function MergeLora(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend_golang']['App']['MergeLora'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function OpenFileFolder(arg1) {
  return window['go']['backend_golang']['App']['OpenFileFolder'](arg1);
}

export function OpenMidiPort(arg1) {
  return window['go']['backend_golang']['App']['OpenMidiPort'](arg1);
}

export function OpenOpenFileDialog(arg1) {
  return window['go']['backend_golang']['App']['OpenOpenFileDialog'](arg1);
}

export function OpenSaveFileDialog(arg1, arg2, arg3) {
  return window['go']['backend_golang']['App']['OpenSaveFileDialog'](arg1, arg2, arg3);
}

export function OpenSaveFileDialogBytes(arg1, arg2, arg3) {
  return window['go']['backend_golang']['App']['OpenSaveFileDialogBytes'](arg1, arg2, arg3);
}

export function PauseDownload(arg1) {
  return window['go']['backend_golang']['App']['PauseDownload'](arg1);
}

export function PlayNote(arg1) {
  return window['go']['backend_golang']['App']['PlayNote'](arg1);
}

export function ReadFileInfo(arg1) {
  return window['go']['backend_golang']['App']['ReadFileInfo'](arg1);
}

export function ReadJson(arg1) {
  return window['go']['backend_golang']['App']['ReadJson'](arg1);
}

export function RestartApp() {
  return window['go']['backend_golang']['App']['RestartApp']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['backend_golang']['App']['SaveFile'](arg1, arg2);
}

export function SaveJson(arg1, arg2) {
  return window['go']['backend_golang']['App']['SaveJson'](arg1, arg2);
}

export function StartFile(arg1) {
  return window['go']['backend_golang']['App']['StartFile'](arg1);
}

export function StartServer(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['backend_golang']['App']['StartServer'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StartWebGPUServer(arg1, arg2) {
  return window['go']['backend_golang']['App']['StartWebGPUServer'](arg1, arg2);
}

export function UpdateApp(arg1) {
  return window['go']['backend_golang']['App']['UpdateApp'](arg1);
}

export function WslCommand(arg1) {
  return window['go']['backend_golang']['App']['WslCommand'](arg1);
}

export function WslEnable(arg1) {
  return window['go']['backend_golang']['App']['WslEnable'](arg1);
}

export function WslInstallUbuntu() {
  return window['go']['backend_golang']['App']['WslInstallUbuntu']();
}

export function WslIsEnabled() {
  return window['go']['backend_golang']['App']['WslIsEnabled']();
}

export function WslStart() {
  return window['go']['backend_golang']['App']['WslStart']();
}

export function WslStop() {
  return window['go']['backend_golang']['App']['WslStop']();
}
