// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function FileInfo(arg1:string):Promise<any>;

export function ReadJson(arg1:string):Promise<any>;

export function SaveJson(arg1:string,arg2:any):Promise<void>;

export function StartServer(arg1:string,arg2:string):Promise<string>;
