// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToDownloadList(arg1, arg2) {
  return ObfuscatedCall(0, [arg1, arg2]);
}

export function CloseMidiPort() {
  return ObfuscatedCall(1, []);
}

export function CmdInteractive(arg1, arg2) {
  return window['go']['backend_golang']['App']['CmdInteractive'](arg1, arg2);
}

export function ContinueDownload(arg1) {
  return ObfuscatedCall(2, [arg1]);
}

export function ConvertData(arg1, arg2, arg3, arg4) {
  return ObfuscatedCall(3, [arg1, arg2, arg3, arg4]);
}

export function ConvertGGML(arg1, arg2, arg3, arg4) {
  return ObfuscatedCall(4, [arg1, arg2, arg3, arg4]);
}

export function ConvertModel(arg1, arg2, arg3, arg4) {
  return ObfuscatedCall(5, [arg1, arg2, arg3, arg4]);
}

export function ConvertSafetensors(arg1, arg2) {
  return ObfuscatedCall(6, [arg1, arg2]);
}

export function ConvertSafetensorsWithPython(arg1, arg2, arg3) {
  return ObfuscatedCall(7, [arg1, arg2, arg3]);
}

export function CopyFile(arg1, arg2) {
  return ObfuscatedCall(8, [arg1, arg2]);
}

export function DeleteFile(arg1) {
  return ObfuscatedCall(9, [arg1]);
}

export function DepCheck(arg1) {
  return ObfuscatedCall(10, [arg1]);
}

export function DownloadFile(arg1, arg2) {
  return ObfuscatedCall(11, [arg1, arg2]);
}

export function FileExists(arg1) {
  return ObfuscatedCall(12, [arg1]);
}

export function GetAbsPath(arg1) {
  return ObfuscatedCall(13, [arg1]);
}

export function GetPlatform() {
  return ObfuscatedCall(14, []);
}

export function GetProxyPort() {
  return ObfuscatedCall(15, []);
}

export function GetPyError() {
  return ObfuscatedCall(16, []);
}

export function InstallPyDep(arg1, arg2) {
  return ObfuscatedCall(17, [arg1, arg2]);
}

export function IsPortAvailable(arg1) {
  return ObfuscatedCall(18, [arg1]);
}

export function ListDirFiles(arg1) {
  return ObfuscatedCall(19, [arg1]);
}

export function MergeLora(arg1, arg2, arg3, arg4, arg5, arg6) {
  return ObfuscatedCall(20, [arg1, arg2, arg3, arg4, arg5, arg6]);
}

export function OpenFileFolder(arg1) {
  return ObfuscatedCall(21, [arg1]);
}

export function OpenMidiPort(arg1) {
  return ObfuscatedCall(22, [arg1]);
}

export function OpenOpenFileDialog(arg1) {
  return ObfuscatedCall(23, [arg1]);
}

export function OpenSaveFileDialog(arg1, arg2, arg3) {
  return ObfuscatedCall(24, [arg1, arg2, arg3]);
}

export function OpenSaveFileDialogBytes(arg1, arg2, arg3) {
  return ObfuscatedCall(25, [arg1, arg2, arg3]);
}

export function PauseDownload(arg1) {
  return ObfuscatedCall(26, [arg1]);
}

export function PlayNote(arg1) {
  return ObfuscatedCall(27, [arg1]);
}

export function ReadFileInfo(arg1) {
  return ObfuscatedCall(28, [arg1]);
}

export function ReadJson(arg1) {
  return ObfuscatedCall(29, [arg1]);
}

export function RestartApp() {
  return ObfuscatedCall(30, []);
}

export function SaveFile(arg1, arg2) {
  return ObfuscatedCall(31, [arg1, arg2]);
}

export function SaveJson(arg1, arg2) {
  return ObfuscatedCall(32, [arg1, arg2]);
}

export function StartFile(arg1) {
  return ObfuscatedCall(33, [arg1]);
}

export function StartServer(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return ObfuscatedCall(34, [arg1, arg2, arg3, arg4, arg5, arg6, arg7]);
}

export function StartWebGPUServer(arg1, arg2) {
  return ObfuscatedCall(35, [arg1, arg2]);
}

export function UpdateApp(arg1) {
  return ObfuscatedCall(36, [arg1]);
}

export function WslCommand(arg1) {
  return ObfuscatedCall(37, [arg1]);
}

export function WslEnable(arg1) {
  return ObfuscatedCall(38, [arg1]);
}

export function WslInstallUbuntu() {
  return ObfuscatedCall(39, []);
}

export function WslIsEnabled() {
  return ObfuscatedCall(40, []);
}

export function WslStart() {
  return ObfuscatedCall(41, []);
}

export function WslStop() {
  return ObfuscatedCall(42, []);
}
