// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertModel(arg1, arg2, arg3) {
  return window['go']['backend_golang']['App']['ConvertModel'](arg1, arg2, arg3);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['backend_golang']['App']['DownloadFile'](arg1, arg2);
}

export function FileExists(arg1) {
  return window['go']['backend_golang']['App']['FileExists'](arg1);
}

export function ListDirFiles(arg1) {
  return window['go']['backend_golang']['App']['ListDirFiles'](arg1);
}

export function OpenFileFolder(arg1) {
  return window['go']['backend_golang']['App']['OpenFileFolder'](arg1);
}

export function ReadFileInfo(arg1) {
  return window['go']['backend_golang']['App']['ReadFileInfo'](arg1);
}

export function ReadJson(arg1) {
  return window['go']['backend_golang']['App']['ReadJson'](arg1);
}

export function SaveJson(arg1, arg2) {
  return window['go']['backend_golang']['App']['SaveJson'](arg1, arg2);
}

export function StartServer(arg1) {
  return window['go']['backend_golang']['App']['StartServer'](arg1);
}
