blank_issues_enabled: true
contact_links:
  - name: Bug and Issue Report
    url: https://github.com/josStorer/RWKV-Runner/issues/new?template=bug_and_issue_report.md
    about: Please follow this template if you are reporting a bug, or your issue may be closed without further notice.
  - name: Bug 和问题反馈
    url: https://github.com/josStorer/RWKV-Runner/issues/new?template=Bug_和问题反馈.md
    about: 请按照模板填写 Bug 和问题反馈，否则你的 Issue 或会被直接关闭。
  - name: Feature Request
    url: https://github.com/josStorer/RWKV-Runner/issues/new?template=feature_request.md
    about: Please follow this template if you are requesting a new feature, or your issue may be closed without further notice.
  - name: 功能建议
    url: https://github.com/josStorer/RWKV-Runner/issues/new?template=功能建议.md
    about: 请按照模板填写功能建议，否则你的 Issue 或会被直接关闭。
